FROM node:24.13.0-alpine3.22

WORKDIR /app

ENV CI=true
ENV PNPM_CONFIG_CONFIRM_MODULES_PURGE=false

COPY package.json ./
COPY pnpm-lock.yaml ./

RUN corepack enable pnpm && pnpm i --frozen-lockfile --config.strict-dep-builds=false

COPY . .

RUN pnpm run build
CMD ["node", "dist/main.js"]

# docker build -f dockerfile.prod -t microservice-name .
# docker run microservice-name
