FROM node:21-alpine3.19

WORKDIR /usr/src/app

COPY package.json ./
COPY yarn.lock ./

RUN yarn install --network-timeout 600000

COPY . .

RUN yarn run build

RUN yarn migration:run

CMD ["node", "dist/main.js"]


# docker build -f dockerfile.prod -t general-microservice .
# docker run general-microservice
